apimServiceName: apiops-devops-da-qa
namedValues: 
loggers:    
diagnostics:
   - name: applicationinsights
     properties:
       verbosity: Error
       loggerId: "/subscriptions/resourceGroups/apiops-devops-qa-rg/providers/Microsoft.ApiManagement/service/apiops-devops-da-qa/loggers/appinsightqa221"
  
apis:
  
    