apimServiceName: [prod or any other target environment apim instance name goes here]
namedValues:
  - name: environment
    properties:
      displayName: environment
      value: "https://www.bing.com"   

apis:
  - name: star-wars
    