name: Feature request
description: Make sure you take a look at the closed issues before opening a new one. Suggest an idea for this project.
title: "[FEATURE REQ]"

body:
  - type: textarea
    id: background
    attributes:
      label: Please describe the feature.
      description: What feature would you like to get added? What problem is it solving?
      placeholder: Feature description
    validations:
      required: true
